// Generated by IcedCoffeeScript 1.6.3-g
var NS, global;



global = this;

NS = function(spec) {
  var ns, part, _i, _len, _ref;
  ns = global;
  _ref = spec.split('.');
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    part = _ref[_i];
    ns = ns[part] != null ? ns[part] : ns[part] = {};
  }
  return ns;
};
